### ISSUE TITLE
Module level code not being fully tested by default

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/pa-aa-toolbox#102]
While developing #100, tests were passing fine on the general code (without specific module tests set), until the classes from the `usgs_ndvi.py` module were explicitly brought into the main `aatoolbox/__init__`. Once there, some errors around importing `get_args()` in Python 3.6 and 3.7 arose.

This would also have arisen once I implemented tests for the module. @Tinkaa recommended I create an issue for this and if it's an easy fix, would be good for all modules to be tested in general for loading of the code. I agree, so here's the issue!

**Comment by turnerm** [comment]
Sorry for taking months to reply! My feeling is that this is not really an issue, as the behaviour you saw makes sense to me -- before adding `usgs_ndvi` to `aatoolbox/__init__`, its import was isolated from the tests, and thus the import issues were not covered. I will close for now but feel free to open the discussion again if you disagree.
