### ISSUE TITLE
Add message when data is overwritten (due to clobber)

### ISSUE THREAD

**Issue by castledan** [OCHA-DAP/pa-aa-toolbox#131]
Add to `check_file_existence` function something like:
`clobber_dict = {True: "", False: "not "}`
`f" Data already present in the folder will {clobber_dict[clobber]}be overwritten."`

**Comment by turnerm** [comment]
It looks like this is taken care of in the latest version, not sure when it was implemented though

**Comment by turnerm** [comment]
Ah oops I read too fast, this is not implemented :woman_facepalming: will keep in the backlog
