### ISSUE TITLE
Update reqs to Python 3.10

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/pa-aa-toolbox#152]

**Comment by caldwellst** [comment]
Discussed with @turnerm on Slack. I will explore the issue and try to tackle it.

- I will see if it's possible to update the reqs directly to 3.11
- I will ensure that the requirements don't conflict

Given complexities, we won't try and explore having requirements files for each version of python. Should thus be as simple as running

``` shell
pip-compile --upgrade
```

Fingers crossed.

**Comment by caldwellst** [comment]
So, in both python 3.10 and 3.11, running into an issue with installing `fiona`. There is an issue with `geopandas` specifying `fiona==1.8.21` when I am compiling, which seems to have [build issues](https://github.com/Toblerity/Fiona/issues/1062). This doesn't exist in 3.9, and there is no trouble in 3.10 or 3.11 installing `fiona==1.8.22`.

In [geopandas/pyproject.toml](https://github.com/geopandas/geopandas/blob/main/pyproject.toml) they specify `fiona>=1.8` so should we explicitly specify `fiona==1.8.22`? Will explore options but thoughts @turnerm ?

**Comment by caldwellst** [comment]
I'm going to stop trying for now as I'm unable to upgrade to 3.10+ without encountering errors that I can't easily resolve.

**Comment by turnerm** [comment]
I tried quickly for Python 3.10, if I run `pip-compile` with `--upgrade`, `fiona` does get bumped. Can you try [this branch](https://github.com/OCHA-DAP/pa-aa-toolbox/commit/50c582b7be4b775f52c5e0eb51b9ba42eecd3a99#diff-2379df6d666a4b1f6478f64a30cfdf87aa1c5dd61a4641b8b269495e197ec59bR179) and see if you get any errors?

**Comment by caldwellst** [comment]
Doh! Yes, it works.

**Comment by caldwellst** [comment]
So, I was also able to now upgrade to 3.11. In both, the testing works. What do you think then about versions? If 3.10, merge your PR, otherwise I can push my changes to the branch and we merge that as 3.11.

**Comment by turnerm** [comment]
Let's do 3.11!

> Noticing that when you ran it, the top-level "automatically produced in 3.9" isn't change to 3.10 (and in mine doesn't change to 3.11). Were we manually setting those messages?

Oops, good catch. It's possible that those don't change once the file is created -- what if you try deleting the files and re-generating them? (You can also just change it by hand of course)

**Comment by caldwellst** [comment]
Upgraded to 3.11 in #161 .
