### ISSUE TITLE
Figure out implementation of doctest for testing

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/pa-aa-toolbox#23]
The Python native doctest module allows the use of docstring examples as tests, to reduce the need to duplicate writing unit tests (and encourage good example documentation). However, when initially testing the implementation of this, test coverage was dramatically increasing, even for functions without doctests in their docstring.

We need to sort out this issue before we can implement doctests. I attempted to generate a response [on SO](https://stackoverflow.com/questions/69749959/why-are-doctest-modules-increasing-test-coverage-in-pytest) and in [#504](https://github.com/github/markup/issues/154) in the pytest-cov repository. When the issue is sorted later down the line, we can easily activate this functionality in the `pa-aa-toolbox` by adding the following lines to the `setup.cfg`:

```
[tool:pytest]
addopts = --doctest-modules
```

**Comment by caldwellst** [comment]
So, reading through the `doctest` documentation, I decided that I would instead try adding in `doctest` to `unittest` discovery, which has now worked as intended, although I would consider that coverage is relatively low still (will need to investigate further). In this method, we explicitly created a function to find and run all `doctest` examples from a specific module. For the `raster` module, the code looks like below:

```python
import unittest
import doctest
from aatoolbox.utils import raster

def load_tests(loader, tests, ignore):
    tests.addTests(doctest.DocTestSuite(raster))
    return tests
```
This is pulled straight from the [`doctest` documentation](https://docs.python.org/2.7/library/doctest.html#unittest-api).

**Comment by turnerm** [comment]
@caldwellst has this been addressed to your satisfaction?

**Comment by caldwellst** [comment]
Ha, yes, sorry, lots of outstanding issues I see you're cleaning. Has worked great!
