### ISSUE TITLE
Specifying correct Python version when running pytest with pyenv

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/pa-aa-toolbox#24]
When testing the `pytest` framework, I ran into an issue where `pytest` didn't recognise the `--cov` argument passed to it. Below is a small example:

```shell
>> pytest --cov=src
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=src
  inifile: None
  rootdir: /Users/caldwellst/Desktop/temp
```

Turns out users of `pyenv` could run into this issue where `pytest` runs off a different version of Python than what is active through `pyenv` (and that version in this case didn't have `pytest-cov` installed). Seems that there has been a fall through in my case with the shims, not sure why, so have to explicitly call `pytest` from my active Python version.

```shell
>> python -m pytest --cov=src
```
This is all based off of [this SO post](https://stackoverflow.com/questions/40718770/pytest-running-with-another-version-of-python). Raising this here in the case we wanted to somehow add this to documentation. It might be too niche to include, but wanted to at least have an issue active for others that may run into it.

**Comment by turnerm** [comment]
@caldwellst thanks for flagging this, could you add a couple of lines about it to CONTRIBUTING.rst and then close?
