### ISSUE TITLE
Implement accessor documentation with Sphinx

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/pa-aa-toolbox#31]
@turnerm found this great extension to Sphinx that helps [autodocument accessors](https://sphinx-autosummary-accessors.readthedocs.io/en/stable/index.html). The implementation of it requires the use of autosummary/autodoc, which I don't think has been fully setup yet for this repo? From my understanding, we will need an `index.rst` file similar to in this [SO post](https://stackoverflow.com/questions/2701998/sphinx-autodoc-is-not-automatic-enough/62613202#62613202) in order to specify the accessors to document specifically.

Leaving this issue here for tackling at a later date, but also @turnerm wanna see if your understanding of how to implement is right or if it is easier to just plug in without creating the `index.rst` file?

**Comment by turnerm** [comment]
@caldwellst I think this is taken care of with `apidoc` but feel free to re-open if I got it wrong!
