### ISSUE TITLE
Determine if we should switch coordinates from -180 to 180 to 0 to 360

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/pa-aa-toolbox#32]
> Honestly this CAMS thing, I would have to double-check as I was doing that in the first weeks I learned about geospatial processing. Haven't used the functionality structurally for anything else than IRI. And it is more standard to use -180 to 180 so I am doubting if we should even provide functionality to convert to 0-360 or that might cause incorrect use.

@Tinkaa wrote the above comment and initially coded the work to convert coordinates between the two systems. However, not sure if it's necessary or appropriate still so best to investigate to determine if useful to have this functionality.

**Edit:** to be explicit, as @turnerm raised in #19, once we've determined what this does (or does not) actually affect in calculations we can get rid of, modify, or leave in place the method as appropriate.

**Comment by Tinkaa** [comment]
Regarding what it does, it was needed when we used `rasterstats.zonal_stats`. Else the coordinates wouldn't match with its assumptions and stats would be wrong. However, I think now that we are using rioxarray to compute stats that is much better at handling coordinate systems, so it might not be an issue anymore, but would have to figure that out to be sure.

**Comment by turnerm** [comment]
@caldwellst should we still keep this discussion open?
