### ISSUE TITLE
Re-use docstring sections using docrep or other functionality

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/pa-aa-toolbox#33]
In some instances, it's useful to re-use docstring sections across different parts of documentation. The [docrep library](https://docrep.readthedocs.io/en/latest/) found by @Tinkaa provides API functionality for this which could be useful. For instance, there are dual methods in the `raster` module such as `compute_raster_stats()` where one builds off another by passing `**kwargs`, but it would be useful for the help documentation of the child method to explicitly list those args. This is the example use case highlighted in the docrep documentation itself.

However, initial attempts by myself to use docrep weren't successful or immediately straightforward, so placing this as an issue here for future reference.

As well, @turnerm also mentioned another possible approach on Slack:

> While I don't find any straightforward solutions, another option is to write a decorator that copies over the __doc__  parameter. Some discussion on SO for [classes](https://stackoverflow.com/questions/17393176/python-3-method-docstring-inheritance-without-breaking-decorators-or-violating) and [functions](https://softwareengineering.stackexchange.com/questions/386755/sharing-docstrings-between-similar-functions), there are probably more.
> 
> However, more broadly, if you find yourself passing parameters across many functions, this is a known anti-pattern called [tramp data](https://softwareengineering.stackexchange.com/a/335013), that may sometimes indicate the need for a refactor (not always the case though of course).

**Comment by turnerm** [comment]
Closing for now as I don't think we have this issue too much, but good to keep as a reference
