### ISSUE TITLE
Automate doc building

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/pa-aa-toolbox#4]
Docs are hosted on github pages from the `gh-pages` branch, this deployment can be automated with github actions, see [here](https://betterprogramming.pub/auto-documenting-a-python-project-using-sphinx-8878f9ddc6e9) and [here](https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/)

**Comment by mcarans** [comment]
Following from our Slack chat, I looked at multiple doc tools and for the HDX Python libraries settled on pydoc-markdown. All the configuration for pydoc-markdown goes into pyproject.toml. It supports things like readthedocs etc., but I like its simplest option, a single markdown file in the root of the repo, which saves having to use GitHub pages eg.

```
[[tool.pydoc-markdown.loaders]]
type = "python"
search_path = ["src"]
packages = ["aatools"]

[tool.pydoc-markdown.renderer]
type = "markdown"
filename = "apidocs.md"

[tool.pydoc-markdown.renderer.source_linker]
type = "github"
repo = "OCHA-DAP/pa-aa-toolbox"

```

and 

```
legacy_tox_ini = """
...
[testenv:docs]
wheel_build_env = py38
deps =
    pydoc-markdown
commands =
    pydoc-markdown
...
"""
```

**Comment by mcarans** [comment]
I changed my mind and investigated readthedocs :-) 

The toml looks like this
```
[[tool.pydoc-markdown.loaders]]
type = "python"
search_path = ["src"]
packages = ["hdx.utilities"]

[tool.pydoc-markdown.renderer]
type = "mkdocs"
output_directory = "docs/build"

[tool.pydoc-markdown.renderer.mkdocs_config]
site_name = "HDX Python Utilities"
theme = "readthedocs"
repo_url = "https://github.com/OCHA-DAP/hdx-python-utilities"

[[tool.pydoc-markdown.renderer.pages]]
title = "Home"
name = "index"
source ="docs/main.md"

[[tool.pydoc-markdown.renderer.pages]]
title = "API Documentation"
contents = [ "*" ]

[tool.pydoc-markdown.renderer.markdown.source_linker]
type = "github"
repo = "OCHA-DAP/hdx-python-utilities"
```

You also need a .readthedocs.yml (unfortunately not in toml) with:
```
version: 2
mkdocs: {}  # tell readthedocs to use mkdocs
python:
  version: 3.7
  install:
  - method: pip
    path: .
  - requirements: docs/.readthedocs-requirements.txt
```

And a docs folder like [this](https://github.com/OCHA-DAP/hdx-python-utilities/tree/main/docs).

I have yet to split up the API docs by module.

**Comment by turnerm** [comment]
Switched to ReadTheDocs in #88
