### ISSUE TITLE
raster invert_coordinates inplace

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-aa-toolbox#55]
For some weird reason the `inplace` argument for `invert_coordinates` is not working in [our raster module](https://github.com/OCHA-DAP/pa-aa-toolbox/blob/1e151de0d089c5599d68126a5e6f103aa34a3f3b/src/aatoolbox/utils/raster.py). 
It does work for calendar functions. I haven't tested if it also doesn't work for other spatial-related functions. 
But we should fix this at some point.

**Comment by caldwellst** [comment]
I'm looking into it and bringing up lots of issues I need to sort through ha. Will be tackling though!

**Comment by caldwellst** [comment]
Addressed in #139
