### ISSUE TITLE
GeoBoundingBox - only allow negative west coordinates? 

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-aa-toolbox#92]
Due to the recent changes we made to the GeoBoundingBox and rethinking IRI, I was thinking if we should restrict the longitude range of GeoBoundingBox to be -180 to 180. 

We already restrict that East>West, which essentially means that the longitude range cannot be on the scale from 0-360, which makes sense imo. 

However, we can still have an input of say west=4 and east=10. While this is valid, I think the most commonly used longitude range is -180 to 180. Sometimes you see two times 0-180 used, where it is specifically specified whether it is West or East. When we do this, i.e. allowing positive values for the west coordinate, we need to do extra checks of the coordinate range for some data sources (e.g. for the IRI maproom downloads). 

Imo opinion it thus makes sense to restrict the west coordinate to be negative, but can also see arguments that it is too restricting. So curious to hear your opinions

**Comment by turnerm** [comment]
This is a really good point, I had not thought of that! 

My initial instinct would be to restrict GeoBoundingBox to the most standard coordinate system, i.e. -180 to 180 for lon and -90 to 90 for lat. Do you think that would cause a problem for anything?

**Comment by Tinkaa** [comment]
Ah yeah good point that this more than just negative values but also restricting ranges, also for latitude. Would agree on restricting.

**Comment by Tinkaa** [comment]
Solved in #94
